/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: /home/byd/Desktop/cyclonedds/examples/demo-localcom/bulid/DemoData.h
  Source: /home/byd/Desktop/cyclonedds/examples/demo-localcom/DemoData.idl
  Cyclone DDS: V0.11.0

*****************************************************************/
#ifndef DDSC__HOME_BYD_DESKTOP_CYCLONEDDS_EXAMPLES_DEMO_LOCALCOM_BULID_DEMODATA_H_4ECAAD8708A053042518844CBA05A154
#define DDSC__HOME_BYD_DESKTOP_CYCLONEDDS_EXAMPLES_DEMO_LOCALCOM_BULID_DEMODATA_H_4ECAAD8708A053042518844CBA05A154

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct DemoData_Msg
{
  int32_t userID;
  char * message;
  uint32_t ntime;
} DemoData_Msg;

extern const dds_topic_descriptor_t DemoData_Msg_desc;

#define DemoData_Msg__alloc() \
((DemoData_Msg*) dds_alloc (sizeof (DemoData_Msg)));

#define DemoData_Msg_free(d,o) \
dds_sample_free ((d), &DemoData_Msg_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC__HOME_BYD_DESKTOP_CYCLONEDDS_EXAMPLES_DEMO_LOCALCOM_BULID_DEMODATA_H_4ECAAD8708A053042518844CBA05A154 */
